#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Sep 27, 2018 04:24:26 PM CST  platform: Windows NT

import sys

try:
    from Tkinter import *
    import Tkinter, tkFileDialog
except ImportError:
    from tkinter import *
    from tkinter import filedialog

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
    
def set_Tk_var():
    global combobox
    combobox = StringVar()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ProcurementAnalyzerUI
    ProcurementAnalyzerUI.vp_start_gui()

